environment:
  name: podinfo-env
  identifier: podinfoenv
  tags: {}
  type: PreProduction
  # REPLACE
  orgIdentifier: <YOUR_ORG_IDENTIFIER>
  # REPLACE
  projectIdentifier: <YOUR_PROJECT_IDENTIFIER>
