# Deploy a *private* Docker Hub image. Harness injects an image pull
# secret from dockerhub-pat via the Docker connector on the service.

pipeline:
  name: secrets-private-registry
  identifier: secretsprivateregistry
  # REPLACE
  projectIdentifier: <YOUR_PROJECT_IDENTIFIER>
  # REPLACE
  orgIdentifier: <YOUR_ORG_IDENTIFIER>
  tags: {}
  gitOpsEnabled: false
  stages:
    - stage:
        name: Deploy
        identifier: deploy
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: false
          service:
            serviceRef: podinfo
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: podinfo_image
                      sources:
                        - identifier: podinfo_image
                          type: DockerRegistry
                          spec:
                            tag: latest
          environment:
            environmentRef: podinfoenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: podinfoinfra
          execution:
            steps:
              - step:
                  name: Rolling Deploy
                  identifier: rolling_deploy
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rolling Rollback
                  identifier: rolling_rollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
